version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: converseo_local_django
    container_name: converseo_local_django
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start


  redis:
    container_name: redis
    image: redis:5
    restart: unless-stopped
    ports:
      - 6379:6379


  frontend:
    container_name: converseo_frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: converseo_frontend_image
    depends_on:
      - django
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d
    ports:
      - 81:80
